This notebook wiil be to have the final dataframe to go into our model.

In [1]:
%store -r ripa_all_combo

Just dropping columns not useful/not important for our model

In [2]:
ripa_all_combo.head()

,stop_id,ori,agency,exp_years,date_stop,time_stop,stopduration,stop_in_response_to_cfs,officer_assignment_key,assignment,...,resulttext,race,reason_for_stop,reason_for_stopcode,reason_for_stop_code_text,reason_for_stop_detail,reason_for_stop_explanation,action,consented,contraband
0,2443,CA0371100,SD,10,2018-07-01,00:01:37,30,0,1,"Patrol, traffic enforcement, field operations",...,647(F) PC - DISORD CONDUCT:ALCOHOL (M) 64005,White,Reasonable Suspicion,64005,647(F) PC - DISORD CONDUCT:ALCOHOL (M) 64005,Officer witnessed commission of a crime,"staggering, unable to safely walk",None,NaN,None
1,2444,CA0371100,SD,18,2018-07-01,00:03:34,10,0,1,"Patrol, traffic enforcement, field operations",...,22349(B) VC - EXC 55MPH SPEED:2 LANE RD (I) 54395,White,Traffic Violation,54106,22350 VC - UNSAFE SPEED:PREVAIL COND (I) 54106,Moving Violation,Speeding,None,NaN,None
2,2447,CA0371100,SD,1,2018-07-01,00:05:43,15,1,10,Other,...,NaN,Hispanic/Latino/a,Reasonable Suspicion,53072,415(1) PC - FIGHT IN PUBLIC PLACE (M) 53072,Matched suspect description,Both parties involved in argument.,Curbside detention,NaN,None
3,2447,CA0371100,SD,1,2018-07-01,00:05:43,15,1,10,Other,...,NaN,Hispanic/Latino/a,Reasonable Suspicion,53072,415(1) PC - FIGHT IN PUBLIC PLACE (M) 53072,Other Reasonable Suspicion of a crime,Both parties engaged in argument.,Curbside detention,NaN,None
4,2448,CA0371100,SD,3,2018-07-01,00:19:06,5,0,1,"Patrol, traffic enforcement, field operations",...,NaN,White,Traffic Violation,54106,22350 VC - UNSAFE SPEED:PREVAIL COND (I) 54106,Moving Violation,UNSAFE DRIVING,None,NaN,None

In [3]:
ripa_data = ripa_all_combo.drop(['ori','agency','intersection','highway_exit','land_mark',
                                'address_street','address_block','address_city','school_name',
                                'beat_name','resulttext','reason_for_stop_code_text','reason_for_stop_detail',
                                'reason_for_stop_explanation'], axis=1)
print(ripa_data.columns)

Index(['stop_id', 'exp_years', 'date_stop', 'time_stop', 'stopduration',
       'stop_in_response_to_cfs', 'officer_assignment_key', 'assignment',
       'isschool', 'beat', 'pid', 'isstudent', 'perceived_limited_english',
       'perceived_age', 'perceived_gender', 'gender_nonconforming', 'gend',
       'gend_nc', 'perceived_lgbt', 'resultkey', 'result', 'code', 'race',
       'reason_for_stop', 'reason_for_stopcode', 'action', 'consented',
       'contraband'],
      dtype='object')

In [4]:
ripa_data.head()

,stop_id,exp_years,date_stop,time_stop,stopduration,stop_in_response_to_cfs,officer_assignment_key,assignment,isschool,beat,...,perceived_lgbt,resultkey,result,code,race,reason_for_stop,reason_for_stopcode,action,consented,contraband
0,2443,10,2018-07-01,00:01:37,30,0,1,"Patrol, traffic enforcement, field operations",0,122,...,No,6,Custodial Arrest without warrant,64005.0,White,Reasonable Suspicion,64005,None,NaN,None
1,2444,18,2018-07-01,00:03:34,10,0,1,"Patrol, traffic enforcement, field operations",0,121,...,No,2,Warning (verbal or written),54395.0,White,Traffic Violation,54106,None,NaN,None
2,2447,1,2018-07-01,00:05:43,15,1,10,Other,0,822,...,No,1,No Action,NaN,Hispanic/Latino/a,Reasonable Suspicion,53072,Curbside detention,NaN,None
3,2447,1,2018-07-01,00:05:43,15,1,10,Other,0,822,...,No,1,No Action,NaN,Hispanic/Latino/a,Reasonable Suspicion,53072,Curbside detention,NaN,None
4,2448,3,2018-07-01,00:19:06,5,0,1,"Patrol, traffic enforcement, field operations",0,614,...,No,1,No Action,NaN,White,Traffic Violation,54106,None,NaN,None

In [5]:
ripa_data = ripa_data.drop(['stop_id','assignment','result','code','reason_for_stopcode'],axis=1)

In [6]:
ripa_data.head()

,exp_years,date_stop,time_stop,stopduration,stop_in_response_to_cfs,officer_assignment_key,isschool,beat,pid,isstudent,...,gender_nonconforming,gend,gend_nc,perceived_lgbt,resultkey,race,reason_for_stop,action,consented,contraband
0,10,2018-07-01,00:01:37,30,0,1,0,122,1,0,...,0,1,NaN,No,6,White,Reasonable Suspicion,None,NaN,None
1,18,2018-07-01,00:03:34,10,0,1,0,121,1,0,...,0,1,NaN,No,2,White,Traffic Violation,None,NaN,None
2,1,2018-07-01,00:05:43,15,1,10,0,822,1,0,...,0,1,NaN,No,1,Hispanic/Latino/a,Reasonable Suspicion,Curbside detention,NaN,None
3,1,2018-07-01,00:05:43,15,1,10,0,822,2,0,...,0,2,NaN,No,1,Hispanic/Latino/a,Reasonable Suspicion,Curbside detention,NaN,None
4,3,2018-07-01,00:19:06,5,0,1,0,614,1,0,...,0,1,NaN,No,1,White,Traffic Violation,None,NaN,None

In [7]:
print(ripa_data.columns)

Index(['exp_years', 'date_stop', 'time_stop', 'stopduration',
       'stop_in_response_to_cfs', 'officer_assignment_key', 'isschool', 'beat',
       'pid', 'isstudent', 'perceived_limited_english', 'perceived_age',
       'perceived_gender', 'gender_nonconforming', 'gend', 'gend_nc',
       'perceived_lgbt', 'resultkey', 'race', 'reason_for_stop', 'action',
       'consented', 'contraband'],
      dtype='object')

In [8]:
ripa_data.dtypes

exp_years                      int64
date_stop                     object
time_stop                     object
stopduration                   int64
stop_in_response_to_cfs        int64
officer_assignment_key         int64
isschool                       int64
beat                           int64
pid                            int64
isstudent                      int64
perceived_limited_english      int64
perceived_age                  int64
perceived_gender              object
gender_nonconforming           int64
gend                           int64
gend_nc                      float64
perceived_lgbt                object
resultkey                      int64
race                          object
reason_for_stop               object
action                        object
consented                     object
contraband                    object
dtype: object

In [9]:
ripa_data = ripa_data.drop(['gend_nc'],axis=1)

In [10]:
ripa_data = ripa_data.drop(['perceived_gender'],axis=1)

Label Encoding rather than one hot encoding bc supposedly it performs better? https://towardsdatascience.com/one-hot-encoding-is-making-your-tree-based-ensembles-worse-heres-why-d64b282b5769

In [11]:
model_data = ripa_data

In [12]:
model_data['perceived_lgbt'] = model_data['perceived_lgbt'].astype('category')
model_data["lgbt_cat"] = model_data["perceived_lgbt"].cat.codes
model_data['race'] = model_data['race'].astype('category')
model_data["race_cat"] = model_data["race"].cat.codes
model_data['reason_for_stop'] = model_data['reason_for_stop'].astype('category')
model_data["stop_cat"] = model_data["reason_for_stop"].cat.codes
model_data['action'] = model_data['action'].astype('category')
model_data["action_cat"] = model_data["action"].cat.codes
model_data['consented'] = model_data['consented'].astype('category')
model_data["consented_cat"] = model_data["consented"].cat.codes
model_data['contraband'] = model_data['contraband'].astype('category')
model_data["contraband_cat"] = model_data["contraband"].cat.codes

In [13]:
model_data.head()

,exp_years,date_stop,time_stop,stopduration,stop_in_response_to_cfs,officer_assignment_key,isschool,beat,pid,isstudent,...,reason_for_stop,action,consented,contraband,lgbt_cat,race_cat,stop_cat,action_cat,consented_cat,contraband_cat
0,10,2018-07-01,00:01:37,30,0,1,0,122,1,0,...,Reasonable Suspicion,None,NaN,None,0,6,6,14,-1,7
1,18,2018-07-01,00:03:34,10,0,1,0,121,1,0,...,Traffic Violation,None,NaN,None,0,6,7,14,-1,7
2,1,2018-07-01,00:05:43,15,1,10,0,822,1,0,...,Reasonable Suspicion,Curbside detention,NaN,None,0,2,6,7,-1,7
3,1,2018-07-01,00:05:43,15,1,10,0,822,2,0,...,Reasonable Suspicion,Curbside detention,NaN,None,0,2,6,7,-1,7
4,3,2018-07-01,00:19:06,5,0,1,0,614,1,0,...,Traffic Violation,None,NaN,None,0,6,7,14,-1,7

In [14]:
model_data.dtypes

exp_years                       int64
date_stop                      object
time_stop                      object
stopduration                    int64
stop_in_response_to_cfs         int64
officer_assignment_key          int64
isschool                        int64
beat                            int64
pid                             int64
isstudent                       int64
perceived_limited_english       int64
perceived_age                   int64
gender_nonconforming            int64
gend                            int64
perceived_lgbt               category
resultkey                       int64
race                         category
reason_for_stop              category
action                       category
consented                    category
contraband                   category
lgbt_cat                         int8
race_cat                         int8
stop_cat                         int8
action_cat                       int8
consented_cat                    int8
contraband_cat                   int8
dtype: object

Dropping the columns that we already encoded.

In [15]:
model_data = model_data.drop(['perceived_lgbt','race','reason_for_stop','action','consented','contraband'],axis=1)

In [16]:
model_data.head()

,exp_years,date_stop,time_stop,stopduration,stop_in_response_to_cfs,officer_assignment_key,isschool,beat,pid,isstudent,...,perceived_age,gender_nonconforming,gend,resultkey,lgbt_cat,race_cat,stop_cat,action_cat,consented_cat,contraband_cat
0,10,2018-07-01,00:01:37,30,0,1,0,122,1,0,...,25,0,1,6,0,6,6,14,-1,7
1,18,2018-07-01,00:03:34,10,0,1,0,121,1,0,...,25,0,1,2,0,6,7,14,-1,7
2,1,2018-07-01,00:05:43,15,1,10,0,822,1,0,...,30,0,1,1,0,2,6,7,-1,7
3,1,2018-07-01,00:05:43,15,1,10,0,822,2,0,...,30,0,2,1,0,2,6,7,-1,7
4,3,2018-07-01,00:19:06,5,0,1,0,614,1,0,...,23,0,1,1,0,6,7,14,-1,7

Forgot to import our libraries

In [17]:
import pandas as pd
import numpy as np
import datetime

Using datetime function to only obtain Month and Hour from date_stop and time_stop

In [18]:
model_data['date_stop'] = pd.to_datetime(model_data['date_stop']).dt.strftime("%m")

In [19]:
model_data['date_stop']

0         07
1         07
2         07
3         07
4         07
          ..
529595    09
529596    09
529597    09
529598    09
529599    09
Name: date_stop, Length: 529600, dtype: object

In [20]:
model_data['time_stop'] = pd.to_datetime(model_data['time_stop']).dt.strftime('%H')

In [21]:
model_data.head()

,exp_years,date_stop,time_stop,stopduration,stop_in_response_to_cfs,officer_assignment_key,isschool,beat,pid,isstudent,...,perceived_age,gender_nonconforming,gend,resultkey,lgbt_cat,race_cat,stop_cat,action_cat,consented_cat,contraband_cat
0,10,07,00,30,0,1,0,122,1,0,...,25,0,1,6,0,6,6,14,-1,7
1,18,07,00,10,0,1,0,121,1,0,...,25,0,1,2,0,6,7,14,-1,7
2,1,07,00,15,1,10,0,822,1,0,...,30,0,1,1,0,2,6,7,-1,7
3,1,07,00,15,1,10,0,822,2,0,...,30,0,2,1,0,2,6,7,-1,7
4,3,07,00,5,0,1,0,614,1,0,...,23,0,1,1,0,6,7,14,-1,7

In [22]:
model_data.dtypes

exp_years                     int64
date_stop                    object
time_stop                    object
stopduration                  int64
stop_in_response_to_cfs       int64
officer_assignment_key        int64
isschool                      int64
beat                          int64
pid                           int64
isstudent                     int64
perceived_limited_english     int64
perceived_age                 int64
gender_nonconforming          int64
gend                          int64
resultkey                     int64
lgbt_cat                       int8
race_cat                       int8
stop_cat                       int8
action_cat                     int8
consented_cat                  int8
contraband_cat                 int8
dtype: object

Transforming date_stop and time_stop from object to intergers

In [23]:
model_data['date_stop'] = model_data['date_stop'].astype(str).astype(int)
model_data['time_stop'] = model_data['time_stop'].astype(str).astype(int)

In [24]:
model_data.dtypes

exp_years                    int64
date_stop                    int64
time_stop                    int64
stopduration                 int64
stop_in_response_to_cfs      int64
officer_assignment_key       int64
isschool                     int64
beat                         int64
pid                          int64
isstudent                    int64
perceived_limited_english    int64
perceived_age                int64
gender_nonconforming         int64
gend                         int64
resultkey                    int64
lgbt_cat                      int8
race_cat                      int8
stop_cat                      int8
action_cat                    int8
consented_cat                 int8
contraband_cat                int8
dtype: object

Creating our target(result column) and splitting the data

In [25]:
import numpy as np

In [26]:
target = np.array(model_data['resultkey'])

In [27]:
model_data = model_data.drop('resultkey',axis = 1)

In [28]:
model_datalist = list(model_data.columns)

In [39]:
%store model_datalist

Stored 'model_datalist' (list)

In [29]:
model_data = np.array(model_data)

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
train_data,test_data,train_target,test_target = train_test_split(model_data,target, test_size=0.2, random_state = 42)

In [34]:
#save data to use in other notebook 

%store train_data
%store test_data
%store train_target
%store test_target

Stored 'train_data' (ndarray)
Stored 'test_data' (ndarray)
Stored 'train_target' (ndarray)
Stored 'test_target' (ndarray)

In [35]:
print('Training Data Shape:', train_data.shape)

Training Data Shape: (423680, 20)

In [36]:
print('Training Target Shape:', train_target.shape)

Training Target Shape: (423680,)

In [37]:
print('Testing Data Shape:', test_data.shape)

Testing Data Shape: (105920, 20)

In [38]:
print('Testing Target Shape:', test_target.shape)

Testing Target Shape: (105920,)