# import necessary libraries

In [1]:
import pandas as pd 
import numpy as np

Import various RIPA datasets and their accompanying dictionaries.
RIPA datasets included: basic (Stop details),actions taken, reason for stop,result of stop,race

In [2]:
#read in dictionary pertaining to ripa basic dataset
url_basic_dict = "https://seshat.datasd.org/pd/ripa_stops_dictionary_datasd.csv"

ripa_basic_dict = pd.read_csv(url_basic_dict)

In [3]:
ripa_basic_dict

,field,field_type,description,possible_values
0,stop_id,int64,unique identifer for stop,NaN
1,ori,str,agency originating identifier,CA0371100 is the SDPD ORI
2,agency,str,agency,SD
3,exp_years,int64,officer years of experience in law enforcement,NaN
4,stopdate,datetime64[ns],date stop occurred,NaN
5,stoptime,str,time stop began,NaN
6,stopduration,int64,duration of time for stop in minutes,NaN
7,stop_in_response_to_cfs,int64,was the stop made in response to a call for se...,"0 = No, 1 = Yes"
8,officer_assignment_key,int64,type of officer assignment at time of stop (code),see assignment attribute for descriptions of c...
9,assignment,str,type of officer assignment at time of stop (de...,https://oag.ca.gov/sites/all/files/agweb/pdfs/...
10,intersection,str,location of stop - intersecting street name,NaN
11,block,float64,location of stop - hundred block,NaN
12,land_mark,str,location of stop - landmark,NaN
13,street,str,location of stop - street name,NaN
14,highway_exit,str,location of stop - highway exit,NaN
15,isschool,int64,did stop occur at a school?,"0 = No, 1 = Yes"
16,school_name,str,name of school where stop occurred,NaN
17,cityname,str,name of city where stop occurred,NaN
18,beat,int64,location of stop - SDPD beat,http://seshat.datasd.org/pd/pd_beat_neighborho...
19,beat_name,str,location of stop - SDPD beat/neighborhood name,NaN
20,pid,int64,unique identifer for person on a stop,NaN
21,isstudent,int64,was person stopped a student?,"0 = No, 1 = Yes"
22,perceived_limited_english,int64,officer's perception that the person stopped h...,"0 = No, 1 = Yes"
23,perceived_age,int64,officer's perception of the approximate age of...,NaN
24,perceived_gender,str,officer's perception of the gender of the pers...,https://oag.ca.gov/sites/all/files/agweb/pdfs/...
25,gender_nonconforming,int64,officer's perception of whether the person sto...,"0 = No, 1 = Yes"
26,gend,int64,officer's perception of the gender of the pers...,see perceivedGender attribute for descriptions...
27,gend_nc,float64,officer's perception of whether the person sto...,"No data = No, 5 = Yes"
28,perceived_lgbt,str,officer's perception of whether the person sto...,"Yes, No"

In [4]:
#read in ripa basic data set
url_basic = "https://seshat.datasd.org/pd/ripa_stops_datasd.csv"

ripa_basic = pd.read_csv(url_basic)

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (12) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [5]:
ripa_basic

,stop_id,ori,agency,exp_years,date_stop,time_stop,stopduration,stop_in_response_to_cfs,officer_assignment_key,assignment,...,beat_name,pid,isstudent,perceived_limited_english,perceived_age,perceived_gender,gender_nonconforming,gend,gend_nc,perceived_lgbt
0,2443,CA0371100,SD,10,2018-07-01,00:01:37,30,0,1,"Patrol, traffic enforcement, field operations",...,Pacific Beach 122,1,0,0,25,Male,0,1,NaN,No
1,2444,CA0371100,SD,18,2018-07-01,00:03:34,10,0,1,"Patrol, traffic enforcement, field operations",...,Mission Beach 121,1,0,0,25,Male,0,1,NaN,No
2,2447,CA0371100,SD,1,2018-07-01,00:05:43,15,1,10,Other,...,El Cerrito 822,1,0,0,30,Male,0,1,NaN,No
3,2447,CA0371100,SD,1,2018-07-01,00:05:43,15,1,10,Other,...,El Cerrito 822,2,0,0,30,Female,0,2,NaN,No
4,2448,CA0371100,SD,3,2018-07-01,00:19:06,5,0,1,"Patrol, traffic enforcement, field operations",...,Ocean Beach 614,1,0,0,23,Male,0,1,NaN,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
529610,478837,CA0371100,SD,1,2021-09-30,17:39:00,120,0,1,"Patrol, traffic enforcement, field operations",...,San Ysidro 712,2,0,0,35,Male,0,1,NaN,No
529611,478845,CA0371100,SD,1,2021-09-30,21:00:00,180,0,1,"Patrol, traffic enforcement, field operations",...,Kearney Mesa 313,1,0,0,18,Male,0,1,NaN,No
529612,478867,CA0371100,SD,1,2021-09-30,15:50:00,20,0,1,"Patrol, traffic enforcement, field operations",...,Midway District 611,1,0,0,30,Male,0,1,NaN,No
529613,478867,CA0371100,SD,1,2021-09-30,15:50:00,20,0,1,"Patrol, traffic enforcement, field operations",...,Midway District 611,2,0,0,30,Female,0,2,NaN,No
529614,478934,CA0371100,SD,15,2021-09-30,22:30:00,120,0,1,"Patrol, traffic enforcement, field operations",...,Clairemont Mesa East 111,1,0,0,20,Male,0,1,NaN,No

In [6]:
url_actions_dictionary = "https://seshat.datasd.org/pd/ripa_actions_taken_dictionary_datasd.csv"
actions_taken_dictionary = pd.read_csv(url_actions_dictionary)
actions_taken_dictionary

,field,field_type,description,possible_values
0,stop_id,int64,unique identifer for stop,NaN
1,pid,int64,unique identifer for person on a stop,NaN
2,action,str,officer's actions toward the person stopped,https://oag.ca.gov/sites/all/files/agweb/pdfs/...
3,consented,str,response by person stopped if officer asked fo...,Yes or blank

In [7]:
#read in ripa actions taken dataset
url_actions = "https://seshat.datasd.org/pd/ripa_actions_taken_datasd.csv"

actions_taken = pd.read_csv(url_actions)

actions_taken

        stop_id  pid                     action consented
0          2443    1                       None       NaN
1          2444    1                       None       NaN
2          2447    1         Curbside detention       NaN
3          2447    2         Curbside detention       NaN
4          2448    1                       None       NaN
...         ...  ...                        ...       ...
825713   478845    1       Patrol car detention       NaN
825714   478867    1                       None       NaN
825715   478867    2                       None       NaN
825716   478934    1       Patrol car detention       NaN
825717   478934    1  Handcuffed or flex cuffed       NaN

[825718 rows x 4 columns]

In [8]:
#read in ripa dataset on reason for stop- dictionary

url_reason_dictionary = "https://seshat.datasd.org/pd/ripa_stop_reason_dictionary_datasd.csv"

reason_dictionary = pd.read_csv(url_reason_dictionary)

reason_dictionary

,field,field_type,description,possible_values
0,stop_id,int64,unique identifer for stop,NaN
1,pid,int64,unique identifer for person on a stop,NaN
2,reason_for_stop,str,primary reason the officer stopped the person,https://oag.ca.gov/sites/all/files/agweb/pdfs/...
3,reason_for_stopcode,str,specific violation if reason for stop is traff...,see reasonForStopCodeText attribute for descri...
4,reason_for_stop_code_text,str,specific violation if reason for stop is traff...,NaN
5,reason_for_stop_detail,str,detailed primary reason the officer stopped th...,https://oag.ca.gov/sites/all/files/agweb/pdfs/...
6,reason_for_stop_explanation,str,brief narrative explaining the reason for the ...,NaN

In [9]:
#read in ripa dataset on reason for stop

url_reason = "https://seshat.datasd.org/pd/ripa_stop_reason_datasd.csv"

reason = pd.read_csv(url_reason)

reason

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,stop_id,pid,reason_for_stop,reason_for_stopcode,reason_for_stop_code_text,reason_for_stop_detail,reason_for_stop_explanation
0,2443.0,1.0,Reasonable Suspicion,64005,647(F) PC - DISORD CONDUCT:ALCOHOL (M) 64005,Officer witnessed commission of a crime,"staggering, unable to safely walk"
1,2444.0,1.0,Traffic Violation,54106,22350 VC - UNSAFE SPEED:PREVAIL COND (I) 54106,Moving Violation,Speeding
2,2447.0,1.0,Reasonable Suspicion,53072,415(1) PC - FIGHT IN PUBLIC PLACE (M) 53072,Matched suspect description,Both parties involved in argument.
3,2447.0,2.0,Reasonable Suspicion,53072,415(1) PC - FIGHT IN PUBLIC PLACE (M) 53072,Other Reasonable Suspicion of a crime,Both parties engaged in argument.
4,2448.0,1.0,Traffic Violation,54106,22350 VC - UNSAFE SPEED:PREVAIL COND (I) 54106,Moving Violation,UNSAFE DRIVING
...,...,...,...,...,...,...,...
545942,478845.0,1.0,Reasonable Suspicion,99990.0,NA - XX AA - COMMUNITY CARETAKING (X) 99990,Matched suspect description,subject meet 5150 criteria
545943,478867.0,1.0,Reasonable Suspicion,32022.0,602 PC - TRESPASSING (M) 32022,Matched suspect description,subject were camping in p lot
545944,478867.0,2.0,Reasonable Suspicion,32022.0,602 PC - TRESPASSING (M) 32022,Matched suspect description,subject camping in p lot
545945,478934.0,1.0,Reasonable Suspicion,13174.0,243(E)(1) PC - BAT:SPOUSE/EX SP/DATE/ETC (M) 1...,Matched suspect description,subject seen hitting a female in the parking lot
545946,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
#read in result of stop dataset dictionary 

url_result_dictionary = "https://seshat.datasd.org/pd/ripa_stop_result_dictionary_datasd.csv"

result_dictionary = pd.read_csv (url_result_dictionary)

result_dictionary

,field,field_type,description,possible_values
0,stop_id,int64,unique identifer for stop,NaN
1,pid,int64,unique identifer for person on a stop,NaN
2,resultkey,int64,outcome(s) of stop (code),see result attribute for descriptions of codes
3,result,str,outcome(s) of stop (description),https://oag.ca.gov/sites/all/files/agweb/pdfs/...
4,code,float64,"specific violation if stop outcome is warning,...",see resultText attribute for descriptions of c...
5,resulttext,str,"specific violation if stop outcome is warning,...",NaN

In [11]:
#read in result of stop dataset 

url_result = "https://seshat.datasd.org/pd/ripa_stop_result_datasd.csv"

result = pd.read_csv(url_result)

result

,stop_id,pid,resultkey,result,code,resulttext
0,2443,1,6,Custodial Arrest without warrant,64005.0,647(F) PC - DISORD CONDUCT:ALCOHOL (M) 64005
1,2444,1,2,Warning (verbal or written),54395.0,22349(B) VC - EXC 55MPH SPEED:2 LANE RD (I) 54395
2,2447,1,1,No Action,NaN,NaN
3,2447,2,1,No Action,NaN,NaN
4,2448,1,1,No Action,NaN,NaN
...,...,...,...,...,...,...
573309,478837,2,1,No Action,NaN,NaN
573310,478845,1,10,Psychiatric hold,NaN,NaN
573311,478867,1,7,Field interview card completed,NaN,NaN
573312,478867,2,7,Field interview card completed,NaN,NaN
573313,478934,1,6,Custodial Arrest without warrant,64005.0,647(F) PC - DISORD CONDUCT:ALCOHOL (M) 64005

In [12]:
#read in race dataset dictionary 

url_race_dictionary = "https://seshat.datasd.org/pd/ripa_race_dictionary_datasd.csv"

race_dictionary = pd.read_csv(url_race_dictionary)

race_dictionary

,field,field_type,description,possible_values
0,stop_id,int64,unique identifer for stop,NaN
1,pid,int64,unique identifer for person on a stop,NaN
2,race,str,officer's perception of the race(s) of the per...,https://oag.ca.gov/sites/all/files/agweb/pdfs/...

In [13]:
#read in race dataset 

url_race = "https://seshat.datasd.org/pd/ripa_race_datasd.csv"

race = pd.read_csv(url_race)

race

        stop_id  pid                    race
0          2443    1                   White
1          2444    1                   White
2          2447    1       Hispanic/Latino/a
3          2447    2       Hispanic/Latino/a
4          2448    1                   White
...         ...  ...                     ...
535210   478837    2       Hispanic/Latino/a
535211   478845    1                   White
535212   478867    1                   White
535213   478867    2                   White
535214   478934    1  Black/African American

[535215 rows x 3 columns]

In [1]:
contraband_dict_url = "https://seshat.datasd.org/pd/ripa_contraband_evid_dictionary_datasd.csv"

contraband_dict = pd.read_csv(contraband_dict_url)

contraband_dict

NameError: name 'pd' is not defined

check shape and nans count for all the datasets (excluding dictionaries)

In [14]:
print(race.shape)
print(result.shape)
print(reason.shape)
print(ripa_basic.shape)
print(actions_taken.shape)
#various shapes indicate that various observations per stop

(535215, 3)
(573314, 6)
(545947, 7)
(529615, 29)
(825718, 4)

In [15]:
#check nans 
ripa_basic.isnull().sum()

stop_id                           0
ori                               0
agency                            0
exp_years                         0
date_stop                         0
time_stop                         0
stopduration                      0
stop_in_response_to_cfs           0
officer_assignment_key            0
assignment                        0
intersection                 477303
address_block                 56032
land_mark                    529554
address_street                22457
highway_exit                 525138
isschool                          0
school_name                  529184
address_city                      1
beat                              0
beat_name                         0
pid                               0
isstudent                         0
perceived_limited_english         0
perceived_age                     0
perceived_gender                152
gender_nonconforming              0
gend                              0
gend_nc                      529337
perceived_lgbt                    0
dtype: int64

alot of missing values in Ripa basic dataset concerning location details
 ...we may be unable to use location as a feature, or at least infer location by the beat reported

In [16]:
actions_taken.isnull().sum()

stop_id           0
pid               0
action            0
consented    804662
dtype: int64

we know all actions taken for all observations in this dataset

In [17]:
reason.isnull().sum()

stop_id                            1
pid                                1
reason_for_stop                    1
reason_for_stopcode            26415
reason_for_stop_code_text      26415
reason_for_stop_detail         26407
reason_for_stop_explanation        3
dtype: int64

In [18]:
reason[reason['pid'].isnull()] #missing row

,stop_id,pid,reason_for_stop,reason_for_stopcode,reason_for_stop_code_text,reason_for_stop_detail,reason_for_stop_explanation
545946,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
result.isnull().sum()

stop_id            0
pid                0
resultkey          0
result             0
code          239672
resulttext    239672
dtype: int64

result dataframe has a lot missing in code/resulttext columns, but these columns are only populated if stop outcome is warning/citation/custodial arrest

In [20]:
race.isnull().sum() #race populated everywhere

stop_id    0
pid        0
race       0
dtype: int64

Merging these datasets will be based on stop_id because this uniquely identifies each stop, whereas pid uniquely identifies individuals in each stop. 

Since there may be multiple individuals per stop_id, we will have multiple observations per stop after the merge

In [21]:
#conduct a inner merge because we want to keep all stop details located in ripa_basic &results 
    #merge is to add additional information not in ripa_basic to those stops 

#keys for merge are stop_id, and pid 

ripa_basic_result = pd.merge(ripa_basic, result, on=['stop_id','pid'])
ripa_basic_result.head()

print(ripa_basic_result.shape) #duplicated

(573335, 33)

In [22]:
ripa_basic_result['stop_id'].nunique()

462461

In [23]:
ripa_basic['stop_id'].nunique()

462461

In [24]:
refined_basic = ripa_basic.drop_duplicates(subset=['stop_id','pid'])
refined_results = result.drop_duplicates(subset = ['stop_id','pid'])

basic_result_combo = pd.merge(refined_basic, refined_results, how='inner', left_on=['stop_id','pid'],right_on=['stop_id','pid'])
print(refined_basic.shape)
print(refined_results.shape)
print(basic_result_combo.shape)

(529600, 29)
(529600, 6)
(529600, 33)

In [25]:
#find duplicated

duplicates=ripa_basic.duplicated(subset=['stop_id','pid'])
duplicates[duplicates].index

Int64Index([ 4175, 10557, 16176, 17385, 19040, 19042, 22634, 27640, 28077,
            28079, 37582, 45910, 49071, 50481, 52113],
           dtype='int64')

In [26]:
print(ripa_basic.iloc[4175])

stop_id                                                               6289
ori                                                              CA0371100
agency                                                                  SD
exp_years                                                                1
date_stop                                                       2018-07-08
time_stop                                                         04:03:00
stopduration                                                            60
stop_in_response_to_cfs                                                  0
officer_assignment_key                                                   1
assignment                   Patrol, traffic enforcement, field operations
intersection                                                           NaN
address_block                                                       4800.0
land_mark                                                              NaN
address_street                                                  cole st #7
highway_exit                                                           NaN
isschool                                                                 0
school_name                                                            NaN
address_city                                                     SAN DIEGO
beat                                                                   115
beat_name                                              University City 115
pid                                                                      2
isstudent                                                                0
perceived_limited_english                                                0
perceived_age                                                           30
perceived_gender                                                    Female
gender_nonconforming                                                     0
gend                                                                     2
gend_nc                                                                NaN
perceived_lgbt                                                          No
Name: 4175, dtype: object

In [27]:
print(ripa_basic.iloc[4174])

stop_id                                                               6289
ori                                                              CA0371100
agency                                                                  SD
exp_years                                                                1
date_stop                                                       2018-07-08
time_stop                                                         04:03:00
stopduration                                                            60
stop_in_response_to_cfs                                                  0
officer_assignment_key                                                   1
assignment                   Patrol, traffic enforcement, field operations
intersection                                                           NaN
address_block                                                       4800.0
land_mark                                                              NaN
address_street                                                  cole st #7
highway_exit                                                           NaN
isschool                                                                 0
school_name                                                            NaN
address_city                                                     SAN DIEGO
beat                                                                   115
beat_name                                              University City 115
pid                                                                      2
isstudent                                                                0
perceived_limited_english                                                0
perceived_age                                                           40
perceived_gender                                                    Female
gender_nonconforming                                                     0
gend                                                                     2
gend_nc                                                                NaN
perceived_lgbt                                                          No
Name: 4174, dtype: object

In [28]:
print(ripa_basic.iloc[4173])

stop_id                                                               6289
ori                                                              CA0371100
agency                                                                  SD
exp_years                                                                1
date_stop                                                       2018-07-08
time_stop                                                         04:03:00
stopduration                                                            60
stop_in_response_to_cfs                                                  0
officer_assignment_key                                                   1
assignment                   Patrol, traffic enforcement, field operations
intersection                                                           NaN
address_block                                                       4800.0
land_mark                                                              NaN
address_street                                                  cole st #7
highway_exit                                                           NaN
isschool                                                                 0
school_name                                                            NaN
address_city                                                     SAN DIEGO
beat                                                                   115
beat_name                                              University City 115
pid                                                                      1
isstudent                                                                0
perceived_limited_english                                                0
perceived_age                                                           40
perceived_gender                                                    Female
gender_nonconforming                                                     0
gend                                                                     2
gend_nc                                                                NaN
perceived_lgbt                                                          No
Name: 4173, dtype: object

there were some duplicate records. From dataframe ripa_basic index 4714, 4715 were duplicated records.

Now to merge on other dataframes: race, reason, and actions taken 
First remove any duplicates based on stop_id and pid, then conduct merge

In [29]:
refined_race = race.drop_duplicates(subset=['stop_id','pid'])

refined_reason = reason.drop_duplicates(subset=['stop_id','pid'])

refined_actions = actions_taken.drop_duplicates(subset=['stop_id','pid'])

In [30]:
df_merge = [basic_result_combo,refined_race, refined_reason, refined_actions]

from functools import reduce #required for easier merging all the dataframes at once

ripa_all_combo = reduce(lambda left, right: pd.merge(left, right, on =['stop_id','pid']),df_merge)

print(ripa_all_combo.shape)

#ripa_all_combo = pd.merge(basic_result_combo, refined_results, how='inner', on=['stop_id','pid'])

(529600, 41)

In [31]:
ripa_all_combo.head()

,stop_id,ori,agency,exp_years,date_stop,time_stop,stopduration,stop_in_response_to_cfs,officer_assignment_key,assignment,...,code,resulttext,race,reason_for_stop,reason_for_stopcode,reason_for_stop_code_text,reason_for_stop_detail,reason_for_stop_explanation,action,consented
0,2443,CA0371100,SD,10,2018-07-01,00:01:37,30,0,1,"Patrol, traffic enforcement, field operations",...,64005.0,647(F) PC - DISORD CONDUCT:ALCOHOL (M) 64005,White,Reasonable Suspicion,64005,647(F) PC - DISORD CONDUCT:ALCOHOL (M) 64005,Officer witnessed commission of a crime,"staggering, unable to safely walk",None,NaN
1,2444,CA0371100,SD,18,2018-07-01,00:03:34,10,0,1,"Patrol, traffic enforcement, field operations",...,54395.0,22349(B) VC - EXC 55MPH SPEED:2 LANE RD (I) 54395,White,Traffic Violation,54106,22350 VC - UNSAFE SPEED:PREVAIL COND (I) 54106,Moving Violation,Speeding,None,NaN
2,2447,CA0371100,SD,1,2018-07-01,00:05:43,15,1,10,Other,...,NaN,NaN,Hispanic/Latino/a,Reasonable Suspicion,53072,415(1) PC - FIGHT IN PUBLIC PLACE (M) 53072,Matched suspect description,Both parties involved in argument.,Curbside detention,NaN
3,2447,CA0371100,SD,1,2018-07-01,00:05:43,15,1,10,Other,...,NaN,NaN,Hispanic/Latino/a,Reasonable Suspicion,53072,415(1) PC - FIGHT IN PUBLIC PLACE (M) 53072,Other Reasonable Suspicion of a crime,Both parties engaged in argument.,Curbside detention,NaN
4,2448,CA0371100,SD,3,2018-07-01,00:19:06,5,0,1,"Patrol, traffic enforcement, field operations",...,NaN,NaN,White,Traffic Violation,54106,22350 VC - UNSAFE SPEED:PREVAIL COND (I) 54106,Moving Violation,UNSAFE DRIVING,None,NaN

In [32]:
print(ripa_all_combo.columns)

Index(['stop_id', 'ori', 'agency', 'exp_years', 'date_stop', 'time_stop',
       'stopduration', 'stop_in_response_to_cfs', 'officer_assignment_key',
       'assignment', 'intersection', 'address_block', 'land_mark',
       'address_street', 'highway_exit', 'isschool', 'school_name',
       'address_city', 'beat', 'beat_name', 'pid', 'isstudent',
       'perceived_limited_english', 'perceived_age', 'perceived_gender',
       'gender_nonconforming', 'gend', 'gend_nc', 'perceived_lgbt',
       'resultkey', 'result', 'code', 'resulttext', 'race', 'reason_for_stop',
       'reason_for_stopcode', 'reason_for_stop_code_text',
       'reason_for_stop_detail', 'reason_for_stop_explanation', 'action',
       'consented'],
      dtype='object')

In [33]:
print(basic_result_combo.columns)

Index(['stop_id', 'ori', 'agency', 'exp_years', 'date_stop', 'time_stop',
       'stopduration', 'stop_in_response_to_cfs', 'officer_assignment_key',
       'assignment', 'intersection', 'address_block', 'land_mark',
       'address_street', 'highway_exit', 'isschool', 'school_name',
       'address_city', 'beat', 'beat_name', 'pid', 'isstudent',
       'perceived_limited_english', 'perceived_age', 'perceived_gender',
       'gender_nonconforming', 'gend', 'gend_nc', 'perceived_lgbt',
       'resultkey', 'result', 'code', 'resulttext'],
      dtype='object')

Dataset that analysis will be conducted on is "ripa_all_combo". This dataset contains uniqely identifying stop_id and accompanying details on individuals (pid) and stop details